name: GitOps Deployment with Sparse Checkout

on:
  push:
    branches:
      - main       # Activa el workflow en cada push a la rama principal
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Configurar Sparse Checkout
- name: Sparse Checkout
  run: |
    git init
    git remote add origin https://github.com/Crash0015/GitOps.git
    git config core.sparseCheckout true
    echo "Dockerfile" >> .git/info/sparse-checkout
    echo "app/" >> .git/info/sparse-checkout
    echo "requirements.txt" >> .git/info/sparse-checkout  # Agrega requirements.txt
    git pull origin main

    # Paso 2: Loguearse en Docker Hub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 3: Construir y subir la imagen Docker
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: krash97/hello-world-web:latest  # Cambiado a tu usuario de Docker Hub

    # Paso 4: Verificar la imagen Docker
    - name: Verify Docker Image
      run: |
        docker pull krash97/hello-world-web:latest
        docker run -d -p 5000:5000 --name hello-world krash97/hello-world-web:latest
        sleep 10                                  # Espera a que el contenedor inicie
        curl -f http://localhost:5000 || exit 1  # Verifica que responde correctamente
